version: '3'
services:
  db:
    build: "./db-server"
    environment:
      MYSQL_ROOT_PASSWORD: 'app_password'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
  app:
    build: .
    environment:
      - PORT=3000
    command: bundle exec pumactl start
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
